### ISSUE TITLE
Readme Cleanup

### ISSUE THREAD

**Issue by techno-disaster** [bartekpacia/mentorship-client#49]
**Describe the bug**
We missed removing the #Future part from readme last time. Remove that and i also found that we had a old backend link in our readme. Update the "hosted dev server link" to our new backend link which can be found [here](https://github.com/anitab-org/mentorship-backend)

Also the first time a contributor opens the folder he will get a lot of errors due to missing packages. We should mention in setup instrucitons to run ```flutter pub get``` in the folder or click the ```get dependencies``` button

**Comment by robotjellyzone** [comment]
Hi @Techno-Disaster i think we can also add one more point in the READme that is when the user/contributor opens the cloned file in the android studio then at that time many errors/warnings may occur so to remove all those errors one should click **get dependencies** [ this will surely serve as a first timers issue for read me] what do you think ?

**Comment by techno-disaster** [comment]
@robotjellyzone yep, thats a good idea. I'll add that in this issue

**Comment by isabelcosta** [comment]
Here's the raw notes from the Flutter setup session regarding improvements to the env setup documentation:

- for example, if I don’t have Android Studio, how could I have AVD (virtual device). Refer:(https://stackoverflow.com/questions/42718973/run-avd-emulator-without-android-studio)
- `flutter pub get` in the README
- Section to run the project, either on the virtual device or physical device
- iOS setup, running a virtual device (EDIT: issue #58 )

@bartekpacia @Techno-Disaster I think these can be made in separate issues, because iOS can be complicated for someone who does not have access to a mac, so it should be made separately.
